import sqlite3

conn = sqlite3.connect('db.sqlite3')
cursor = conn.cursor()
cursor.execute("SELECT id, rating, title, description, main_pic FROM app_records ORDER BY rating DESC LIMIT 5")
popular_records = cursor.fetchall()
conn.close()

with open('templates/popular_records_template.html', 'w') as template:
    print('<div class="row" style="padding: 0 15px;">', file=template)
    print('    <div id="post-{}" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 post-sidebar-top">'.format(popular_records[0][0]), file=template)
    print('        <div class="rating"><span><span class="post-ratings__results">{} </span><span class="eee">из 10</span></span>'.format(popular_records[0][1]), file=template)
    print('        </div>', file=template)
    print('        <div class="post-wrap-h2">', file=template)
    print('            <h2><a href="/r{}">{}</a></h2></div>'.format(popular_records[0][0], popular_records[0][2]), file=template)
    print('        <div class="excerpt clip">', file=template)
    print('            <p>{}</p>'.format(popular_records[0][3]), file=template)
    print('        </div>', file=template)
    print('    </div>', file=template)
    print('</div>', file=template)
    print('<div class="triangle2">', file=template)
    print('    <div class="row">', file=template)
    print('        <div class="col-xs-12 col-sm-6 col-md-6 post-green-sidebar post-sidebar-2 pr-0">', file=template)
    print('            <article id="post-{}" class="post-{} post type-post status-publish format-standard has-post-thumbnail hentry category-general tag">'.format(popular_records[1][0], popular_records[1][0]), file=template)
    print('                <div class="row post-sidebar-cropped post-sidebar-overlay" style="margin: 0; background: url(/media/{})no-repeat;background-size: cover;">'.format(popular_records[1][4]), file=template)
    print('                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">', file=template)
    print('                        <div class="post-wrap-sidebar">', file=template)
    print('                            <div class="rating"><span><span class="post-ratings__results">{}</span></span>'.format(popular_records[1][1]), file=template)
    print('                            </div>', file=template)
    print('                            <div class="post-wrap-h2">', file=template)
    print('                                <h2><a href="/r{}">{}</a></h2></div>'.format(popular_records[1][0], popular_records[1][2]), file=template)
    print('                            <div class="excerpt clip">{}</div>'.format(popular_records[1][3] ), file=template)
    print('                        </div>', file=template)
    print('                    </div>', file=template)
    print('                </div>', file=template)
    print('            </article>', file=template)
    print('        </div>', file=template)
    print('        <div class="col-xs-12 col-sm-6 col-md-6 post-green-sidebar post-sidebar-1 pl-0">', file=template)
    print('            <article id="post-{}" class="post-{} post type-post status-publish format-standard has-post-thumbnail hentry category-general tag">'.format(popular_records[2][0], popular_records[2][0]), file=template)
    print('                <div class="row post-sidebar-cropped post-sidebar-overlay" style="margin: 0; background: #51b956;">', file=template)
    print('                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">', file=template)
    print('                        <div class="post-wrap-sidebar">', file=template)
    print('                            <div class="rating"><span><span class="post-ratings__results">{}</span></span>'.format(popular_records[2][1]), file=template)
    print('                            </div>', file=template)
    print('                            <div class="post-wrap-h2">', file=template)
    print('                                <h2><a href="/r{}">{}</a></h2></div>'.format(popular_records[2][0], popular_records[2][2]), file=template)
    print('                            <div class="excerpt clip">', file=template)
    print('                                <p>{}</p>'.format(popular_records[2][3]), file=template)
    print('                            </div>', file=template)
    print('                        </div>', file=template)
    print('                    </div>', file=template)
    print('                </div>', file=template)
    print('            </article>', file=template)
    print('        </div>', file=template)
    print('    </div>', file=template)
    print('    <div class="row">', file=template)
    print('        <div class="col-xs-12 col-sm-6 col-md-6 post-green-sidebar post-sidebar-2 pr-0">', file=template)
    print('            <article id="post-{}" class="post-{} post type-post status-publish format-standard has-post-thumbnail hentry category-general tag">'.format(popular_records[3][0], popular_records[3][0]), file=template)
    print('                <div class="row post-sidebar-cropped post-sidebar-overlay" style="margin: 0; background: #51b956;">', file=template)
    print('                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">', file=template)
    print('                        <div class="post-wrap-sidebar">', file=template)
    print('                            <div class="rating"><span><span class="post-ratings__results">{}</span></span>'.format(popular_records[3][1]), file=template)
    print('                            </div>', file=template)
    print('                            <div class="post-wrap-h2">', file=template)
    print('                                <h2><a href="/r{}">{}</a></h2></div>'.format(popular_records[3][0], popular_records[3][2]), file=template)
    print('                            <div class="excerpt clip">', file=template)
    print('                                <p>{}</p>'.format(popular_records[3][3]), file=template)
    print('                            </div>', file=template)
    print('                        </div>', file=template)
    print('                    </div>', file=template)
    print('                </div>', file=template)
    print('            </article>', file=template)
    print('        </div>', file=template)
    print('        <div class="col-xs-12 col-sm-6 col-md-6 post-green-sidebar post-sidebar-1 pl-0">', file=template)
    print('            <article id="post-{}" class="post-{} post type-post status-publish format-standard has-post-thumbnail hentry category-general tag">'.format(popular_records[4][0], popular_records[4][0]), file=template)
    print('                <div class="row post-sidebar-cropped post-sidebar-overlay" style="margin: 0; background: url(/media/{})no-repeat;background-size: cover;">'.format(popular_records[4][4]), file=template)
    print('                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">', file=template)
    print('                        <div class="post-wrap-sidebar">', file=template)
    print('                            <div class="rating"><span><span class="post-ratings__results">{}</span></span>'.format(popular_records[4][1]), file=template)
    print('                            </div>', file=template)
    print('                            <div class="post-wrap-h2">', file=template)
    print('                                <h2><a href="/r{}">{}</a></h2></div>'.format(popular_records[4][0], popular_records[4][2]), file=template)
    print('                            <div class="excerpt clip">', file=template)
    print('                                <p>{}</p>'.format(popular_records[4][3]), file=template)
    print('                            </div>', file=template)
    print('                        </div>', file=template)
    print('                    </div>', file=template)
    print('                </div>', file=template)
    print('            </article>', file=template)
    print('        </div>', file=template)
    print('    </div>', file=template)
    print('</div>', file=template)