# Generated by Django 2.2.2 on 2019-06-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='records',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
