# Generated by Django 2.2.2 on 2019-06-18 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190618_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 18, 19, 52, 28, 962659)),
        ),
    ]
