# Generated by Django 2.2.2 on 2019-06-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190618_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
