# Generated by Django 2.2.2 on 2019-06-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_records_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='main_pic',
            field=models.FilePathField(default=None),
        ),
    ]
