# Generated by Django 2.2.2 on 2019-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_useractivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='author',
            field=models.TextField(default='arcturus5340'),
        ),
    ]
