# Generated by Django 2.2.2 on 2019-06-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_records_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='audio',
        ),
        migrations.AddField(
            model_name='records',
            name='media',
            field=models.TextField(default='/static/record_src/r1/media/01. Balls To The Wall.mp3'),
        ),
    ]
