# Generated by Django 2.2.2 on 2019-06-23 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190622_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 23, 19, 22, 2, 461582)),
        ),
    ]
