# Generated by Django 2.2.2 on 2019-06-25 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190625_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 25, 8, 55, 51, 300429)),
        ),
    ]
