# Generated by Django 2.2.2 on 2019-06-25 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190625_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('text', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2019, 6, 25, 9, 24, 49, 875833))),
            ],
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 25, 9, 24, 49, 875404)),
        ),
    ]
