# Generated by Django 2.2.2 on 2019-06-27 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190626_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
