# Generated by Django 2.2.2 on 2019-06-27 07:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190627_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.IntegerField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
