# Generated by Django 2.2.2 on 2019-06-28 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190627_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 28, 7, 26, 42, 265841)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 28, 7, 26, 42, 265408, tzinfo=utc)),
        ),
    ]
