# Generated by Django 2.2.2 on 2019-06-30 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190628_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 30, 5, 54, 51, 549204)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True, default='/media/avatars/avatar-default.png', null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 30, 5, 54, 51, 548791, tzinfo=utc)),
        ),
    ]
