# Generated by Django 2.2.2 on 2019-07-05 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190705_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('name', models.TextField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 9, 42, 9, 957340)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 9, 42, 9, 956604)),
        ),
        migrations.AlterField(
            model_name='records',
            name='media',
            field=models.TextField(default='1, 2, 3, 4'),
        ),
    ]
