# Generated by Django 2.2.2 on 2019-07-05 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190705_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='name',
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 9, 43, 24, 161812)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 9, 43, 24, 161063)),
        ),
    ]
