# Generated by Django 2.2.2 on 2019-07-05 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20190705_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='best_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='records',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='records',
            name='worst_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 10, 41, 8, 914738)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 10, 41, 8, 913968)),
        ),
    ]
