# Generated by Django 2.2.2 on 2019-07-05 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20190705_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 10, 44, 21, 732827)),
        ),
        migrations.AlterField(
            model_name='records',
            name='best_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 10, 44, 21, 732043)),
        ),
        migrations.AlterField(
            model_name='records',
            name='worst_rating',
            field=models.IntegerField(default=10),
        ),
    ]
