# Generated by Django 2.2.2 on 2019-07-05 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20190705_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 10, 54, 31, 597691)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 10, 54, 31, 596908)),
        ),
    ]
