# Generated by Django 2.2.2 on 2019-07-05 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190705_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='rated_users',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 11, 15, 26, 423840)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 11, 15, 26, 422953)),
        ),
    ]
