# Generated by Django 2.2.2 on 2019-07-06 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190705_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='avatar',
            field=models.TextField(blank=True, default='/media/avatars/avatar-default.png', null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='includes',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='records',
            name='pre_video',
            field=models.TextField(default='/static/'),
        ),
        migrations.AddField(
            model_name='records',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 6, 18, 53, 12, 215740)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 6, 18, 53, 12, 214870)),
        ),
    ]
