# Generated by Django 2.2.2 on 2019-07-09 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20190708_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='data',
        ),
        migrations.AddField(
            model_name='media',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file10',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file11',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file12',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file13',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file14',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file15',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file16',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file17',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file18',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file19',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file20',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file21',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file22',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file23',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file24',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file25',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file6',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file7',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file8',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file9',
            field=models.FileField(blank=True, null=True, upload_to='record_src/'),
        ),
        migrations.AddField(
            model_name='records',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 5, 1, 39, 247868)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 5, 1, 39, 246242)),
        ),
        migrations.AlterField(
            model_name='records',
            name='main_pic',
            field=models.FileField(upload_to='record_src/'),
        ),
        migrations.AlterField(
            model_name='records',
            name='pre_video',
            field=models.FileField(blank=True, upload_to='record_src/'),
        ),
    ]
