# Generated by Django 2.2.2 on 2019-07-09 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190709_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='visitors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 8, 51, 29, 501685)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 8, 51, 29, 499940)),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 8, 51, 29, 502029)),
        ),
    ]
