# Generated by Django 2.2.2 on 2019-07-09 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20190709_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 9, 8, 14, 352480)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 9, 8, 14, 350859)),
        ),
        migrations.AlterField(
            model_name='records',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='records',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 9, 8, 14, 352818)),
        ),
    ]
