# Generated by Django 2.2.2 on 2019-07-09 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20190709_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 9, 14, 51, 920905)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 9, 14, 51, 919322)),
        ),
        migrations.AlterField(
            model_name='records',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 9, 14, 51, 921259)),
        ),
    ]
