# Generated by Django 2.2.2 on 2019-07-09 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20190709_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 9, 15, 3, 894630)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 9, 15, 3, 893011)),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 9, 15, 3, 894976)),
        ),
    ]
