# Generated by Django 2.2.2 on 2019-07-09 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20190709_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='provided_users',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 9, 56, 4, 241590)),
        ),
        migrations.AlterField(
            model_name='records',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='records',
            name='best_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 9, 56, 4, 240092)),
        ),
        migrations.AlterField(
            model_name='records',
            name='includes',
            field=models.TextField(default='-', max_length=300),
        ),
        migrations.AlterField(
            model_name='records',
            name='pre_video',
            field=models.FileField(upload_to='record_src/'),
        ),
        migrations.AlterField(
            model_name='records',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='records',
            name='tags',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 9, 56, 4, 241922)),
        ),
    ]
