# Generated by Django 2.2.2 on 2019-07-09 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20190709_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='visitors',
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 10, 16, 34, 375482)),
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 10, 16, 34, 373950)),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 10, 16, 34, 375830)),
        ),
    ]
